version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://thakurdeepraj51:kzMRVrdH6-d2ZU@cluster0.j4pmv.mongodb.net/campusconnect?retryWrites=true&w=majority
      - JWT_SECRET=yourVerySecretKey